"""iMessage sidecar client — the loopback-HTTP contract to the local Hermes "photon" sidecar.

There is no pure-Python path to Apple iMessage: the live link is Photon Spectrum's long-lived gRPC
stream, reachable only through the TypeScript ``spectrum-ts`` SDK. The supported design is therefore a
**two-hop** one — this Python plugin speaks plain loopback HTTP to a local Node **sidecar**, and the
sidecar holds the gRPC stream to the Photon cloud. From the plugin's point of view the *only*
transport is HTTP to ``http://127.0.0.1:8789`` (configurable): a long-lived ``GET /inbound`` NDJSON
stream for inbound, and ``POST /send`` for outbound. No webhook, no public URL, no signing secret —
auth is a shared bearer token carried in the ``X-Hermes-Sidecar-Token`` header (a constant, *not*
``Authorization: Bearer``), and the whole channel is loopback-only.

The Node sidecar itself is an external prerequisite the operator runs (it owns the Photon project
credentials and the gRPC reconnect/replay); this plugin never spawns it. It just needs a reachable
sidecar URL + the shared token, so the client is a thin ``httpx`` wrapper and stays trivially testable
via ``httpx.MockTransport``.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, AsyncIterator, Mapping

import httpx

from tabvis.channels.plugins._platform.config import env_bool, env_required, env_str

# The sidecar hard-caps a single message at 8000 chars (it truncates); truncate here too so the
# receipt reflects what was actually sent rather than silently losing the tail server-side.
MAX_TEXT_LEN = 8000

# Auth is a shared secret in a custom header, constant-time compared by the sidecar — deliberately
# NOT ``Authorization: Bearer`` (this is a loopback control channel, not an OAuth-style API).
TOKEN_HEADER = "X-Hermes-Sidecar-Token"


class IMessageSidecarError(RuntimeError):
    """The sidecar returned a non-success envelope (non-200, or ``{"ok": false}``)."""

    def __init__(self, message: str, *, status: int | None = None, detail: Any = None) -> None:
        super().__init__(message)
        self.status = status
        self.detail = detail


@dataclass
class IMessageConfig:
    """One configured iMessage channel = one reachable sidecar.

    Only the loopback contract lives here. The upstream Photon project id/secret and Spectrum host are
    the *sidecar's* environment (it holds the gRPC link), never the plugin's, so they are intentionally
    absent — the plugin authenticates to the sidecar with ``sidecar_token`` alone.
    """

    sidecar_token: str                              # shared bearer for the loopback control channel
    sidecar_url: str = "http://127.0.0.1:8789"      # loopback base (PHOTON_SIDECAR_BIND:PORT)
    markdown: bool = True                           # send format:"markdown" vs stripped "text"
    channel_account_id: str = "ca_imessage"         # the single account this client-loop plugin serves
    request_timeout: float = 15.0                   # send timeout; the inbound stream uses timeout=None

    @property
    def send_format(self) -> str:
        # The sidecar accepts only "text" | "markdown"; it defaults to "text" when omitted, so we
        # always send an explicit value derived from config.
        return "markdown" if self.markdown else "text"

    @classmethod
    def from_env(cls, env: Mapping[str, str] | None = None) -> "IMessageConfig":
        # The token MUST be set explicitly: this plugin is an out-of-process client of the sidecar, and
        # the sidecar only accepts an explicit shared token for out-of-process senders (an autogenerated
        # per-process token would never match).
        token = env_required("TABVIS_IMESSAGE_SIDECAR_TOKEN", env=env)
        url = env_str("TABVIS_IMESSAGE_SIDECAR_URL", "http://127.0.0.1:8789", env=env)
        return cls(
            sidecar_token=token,
            sidecar_url=url.rstrip("/"),
            markdown=env_bool("TABVIS_IMESSAGE_MARKDOWN", True, env=env),
            channel_account_id=env_str("TABVIS_IMESSAGE_CHANNEL_ACCOUNT_ID", "ca_imessage", env=env),
        )


class IMessageSidecarClient:
    """Thin ``httpx`` client for the sidecar's loopback HTTP API (``/send`` + ``/inbound``)."""

    def __init__(self, config: IMessageConfig, *, client: httpx.AsyncClient | None = None) -> None:
        self._config = config
        self._base = config.sidecar_url.rstrip("/")
        self._client = client
        self._owns_client = client is None

    def _http(self) -> httpx.AsyncClient:
        if self._client is None:
            self._client = httpx.AsyncClient(timeout=self._config.request_timeout)
        return self._client

    def _headers(self) -> dict[str, str]:
        return {TOKEN_HEADER: self._config.sidecar_token}

    async def send_text(self, space_id: str, text: str, *, fmt: str | None = None) -> str:
        """``POST /send`` a plain/markdown message to a conversation; returns the sidecar ``messageId``.

        ``space_id`` is the inbound ``space.id`` (an E.164 phone for a DM, an opaque GUID for a group);
        the sidecar resolves/creates the underlying iMessage space. Success is HTTP 200 **and**
        ``{"ok": true}``; anything else raises so :meth:`deliver` can turn it into a failed receipt.
        """
        body = {
            "spaceId": space_id,
            "text": text[:MAX_TEXT_LEN],
            "format": fmt or self._config.send_format,
        }
        response = await self._http().post(f"{self._base}/send", json=body, headers=self._headers())
        data = _json_obj(response)
        if response.status_code != 200 or not data.get("ok"):
            raise IMessageSidecarError(
                str(data.get("error") or f"sidecar /send failed (HTTP {response.status_code})"),
                status=response.status_code,
                detail=data,
            )
        # messageId may be null even on success; the caller records it (for tapback routing) as-is.
        return str(data.get("messageId") or "")

    async def open_inbound(self) -> AsyncIterator[dict[str, Any]]:
        """One long-lived ``GET /inbound`` connection: yield each NDJSON event dict.

        The body is newline-delimited JSON, one object per line, with a blank line every ~25s as a
        keepalive heartbeat (skipped). ``timeout=None`` because the connection is held open
        indefinitely. This yields until the connection closes; :meth:`stream_inbound` re-opens it.
        """
        async with self._http().stream(
            "GET", f"{self._base}/inbound", headers=self._headers(), timeout=None
        ) as response:
            response.raise_for_status()
            async for line in response.aiter_lines():
                stripped = line.strip()
                if not stripped:
                    continue  # heartbeat keepalive — no payload
                try:
                    event = json.loads(stripped)
                except ValueError:
                    continue  # a malformed line is skipped, never fatal to the stream
                if isinstance(event, dict):
                    yield event

    async def stream_inbound(self) -> AsyncIterator[dict[str, Any]]:
        """The default live source: re-open ``/inbound`` on drop with 1s→30s exponential backoff.

        The sidecar owns the gRPC reconnect + at-least-once catch-up replay, so the plugin's only job
        is to keep the HTTP stream open; a dropped connection is expected (sidecar restart, transient
        network) and simply re-opened. Cancellation (channel stop) propagates out cleanly.
        """
        import asyncio

        backoff = 1.0
        while True:
            try:
                async for event in self.open_inbound():
                    backoff = 1.0  # a delivered line proves the stream is healthy — reset backoff
                    yield event
            except asyncio.CancelledError:
                raise
            except Exception:  # noqa: BLE001 - any transport error just triggers a backed-off re-open
                pass
            await asyncio.sleep(backoff)
            backoff = min(backoff * 2.0, 30.0)

    async def aclose(self) -> None:
        if self._client is not None and self._owns_client:
            await self._client.aclose()
            self._client = None


def _json_obj(response: httpx.Response) -> dict[str, Any]:
    try:
        data = response.json()
    except Exception:  # noqa: BLE001 - a non-JSON body becomes an empty envelope, not a crash
        return {}
    return data if isinstance(data, dict) else {"data": data}
